[package]
name = "asfmrs"
version = "0.2.0"
authors = ["Adam Greig <adam@adamgreig.com>"]

[dependencies]
airspy = "*"
portaudio = "*"
rustc-serialize = "*"

[dependencies.sdr]
path = "/home/adam/Projects/sdr-rs"
